version: "3"

tasks:
  prerelease:
    cmds:
      - commit-and-tag-version -p rc
      - git push --follow-tags origin main
  release:
    cmds:
      - commit-and-tag-version
      - git push --follow-tags origin main
  deploy:helm:
    requires:
      vars:
        - CONFIG_FILE
        - KUBE_CONTEXT
    dir: ./helm/charts/
    cmds:
      - helm upgrade --kube-context "{{.KUBE_CONTEXT}}" --install stwhh-mensa ./stwhh-mensa/ -f "{{.CONFIG_FILE}}"
