name: "Build"
run-name: "Build"
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.5'
      - run: go version

      - run: go mod tidy
      - run: go build -o stwhh-mensa_linux-amd64 main.go
